//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsTag.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandOutput {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandOutput() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsTag.Resources.CommandOutput", typeof(CommandOutput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted &apos;{0}&apos;..
        /// </summary>
        internal static string BulkDeletedFile {
            get {
                return ResourceManager.GetString("BulkDeletedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string BulkDeleteFileMissing {
            get {
                return ResourceManager.GetString("BulkDeleteFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized to delete &apos;{0}&apos;, skipping..
        /// </summary>
        internal static string BulkDeleteUnauthorized {
            get {
                return ResourceManager.GetString("BulkDeleteUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extra config property &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string ConfigExtraPropertyMissing {
            get {
                return ResourceManager.GetString("ConfigExtraPropertyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration &apos;{0}&apos; does not exist.&quot;.
        /// </summary>
        internal static string ConfigMissing {
            get {
                return ResourceManager.GetString("ConfigMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed config property &apos;{0}&apos;..
        /// </summary>
        internal static string ConfigRemove {
            get {
                return ResourceManager.GetString("ConfigRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not valid JSON: {1}.
        /// </summary>
        internal static string ConfigSetInvalidJson {
            get {
                return ResourceManager.GetString("ConfigSetInvalidJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string DirectoryMissing {
            get {
                return ResourceManager.GetString("DirectoryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; already exists in the tag index..
        /// </summary>
        internal static string FileIndexAddDuplicate {
            get {
                return ResourceManager.GetString("FileIndexAddDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added &apos;{0}&apos; to the tag index..
        /// </summary>
        internal static string FileIndexAddItem {
            get {
                return ResourceManager.GetString("FileIndexAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string FileIndexAddMissing {
            get {
                return ResourceManager.GetString("FileIndexAddMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully cleared tag index..
        /// </summary>
        internal static string FileIndexClear {
            get {
                return ResourceManager.GetString("FileIndexClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing &apos;{0}&apos; from the index..
        /// </summary>
        internal static string FileIndexRemoveItem {
            get {
                return ResourceManager.GetString("FileIndexRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to remove. Terminating early..
        /// </summary>
        internal static string FileIndexRemoveNone {
            get {
                return ResourceManager.GetString("FileIndexRemoveNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A JsonReaderException occured while reading {0}: {1}. This usually means your config file is corrupted. Either attempt to fix it or reinstall FsTag..
        /// </summary>
        internal static string ParseJsonReaderException {
            get {
                return ResourceManager.GetString("ParseJsonReaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a recognized print key..
        /// </summary>
        internal static string PrintKeyNotFound {
            get {
                return ResourceManager.GetString("PrintKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid session name, contains {0}.&quot;.
        /// </summary>
        internal static string SessionCreateInvalidName {
            get {
                return ResourceManager.GetString("SessionCreateInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string SessionMissing {
            get {
                return ResourceManager.GetString("SessionMissing", resourceCulture);
            }
        }
    }
}
