//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsTag.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommandOutput {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommandOutput() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FsTag.Resources.CommandOutput", typeof(CommandOutput).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string PrintKeyNotFound {
            get {
                return ResourceManager.GetString("PrintKeyNotFound", resourceCulture);
            }
        }
        
        internal static string ParseJsonReaderException {
            get {
                return ResourceManager.GetString("ParseJsonReaderException", resourceCulture);
            }
        }
        
        internal static string BulkDeletedFile {
            get {
                return ResourceManager.GetString("BulkDeletedFile", resourceCulture);
            }
        }
        
        internal static string BulkDeleteUnauthorized {
            get {
                return ResourceManager.GetString("BulkDeleteUnauthorized", resourceCulture);
            }
        }
        
        internal static string BulkDeleteFileMissing {
            get {
                return ResourceManager.GetString("BulkDeleteFileMissing", resourceCulture);
            }
        }
        
        internal static string FileIndexAddDuplicate {
            get {
                return ResourceManager.GetString("FileIndexAddDuplicate", resourceCulture);
            }
        }
        
        internal static string FileIndexAddMissing {
            get {
                return ResourceManager.GetString("FileIndexAddMissing", resourceCulture);
            }
        }
        
        internal static string FileIndexAddItem {
            get {
                return ResourceManager.GetString("FileIndexAddItem", resourceCulture);
            }
        }
        
        internal static string FileIndexRemoveItem {
            get {
                return ResourceManager.GetString("FileIndexRemoveItem", resourceCulture);
            }
        }
        
        internal static string FileIndexRemoveNone {
            get {
                return ResourceManager.GetString("FileIndexRemoveNone", resourceCulture);
            }
        }
        
        internal static string FileIndexClear {
            get {
                return ResourceManager.GetString("FileIndexClear", resourceCulture);
            }
        }
        
        internal static string ConfigMissing {
            get {
                return ResourceManager.GetString("ConfigMissing", resourceCulture);
            }
        }
        
        internal static string ConfigSetInvalidJson {
            get {
                return ResourceManager.GetString("ConfigSetInvalidJson", resourceCulture);
            }
        }
        
        internal static string ConfigExtraPropertyMissing {
            get {
                return ResourceManager.GetString("ConfigExtraPropertyMissing", resourceCulture);
            }
        }
        
        internal static string ConfigRemove {
            get {
                return ResourceManager.GetString("ConfigRemove", resourceCulture);
            }
        }
        
        internal static string DirectoryMissing {
            get {
                return ResourceManager.GetString("DirectoryMissing", resourceCulture);
            }
        }
        
        internal static string SessionCreateInvalidName {
            get {
                return ResourceManager.GetString("SessionCreateInvalidName", resourceCulture);
            }
        }
        
        internal static string SessionMissing {
            get {
                return ResourceManager.GetString("SessionMissing", resourceCulture);
            }
        }
        
        internal static string BulkDeleteCompleted {
            get {
                return ResourceManager.GetString("BulkDeleteCompleted", resourceCulture);
            }
        }
        
        internal static string BulkMoveUnauthorized {
            get {
                return ResourceManager.GetString("BulkMoveUnauthorized", resourceCulture);
            }
        }
        
        internal static string BulkCopyUnauthorized {
            get {
                return ResourceManager.GetString("BulkCopyUnauthorized", resourceCulture);
            }
        }
        
        internal static string BulkMoveCompleted {
            get {
                return ResourceManager.GetString("BulkMoveCompleted", resourceCulture);
            }
        }
        
        internal static string BulkCopyCompleted {
            get {
                return ResourceManager.GetString("BulkCopyCompleted", resourceCulture);
            }
        }
    }
}
