//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsTag.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Descriptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Descriptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FsTag.Resources.Descriptions", typeof(Descriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TagCommand {
            get {
                return ResourceManager.GetString("TagCommand", resourceCulture);
            }
        }
        
        internal static string PrintCommand {
            get {
                return ResourceManager.GetString("PrintCommand", resourceCulture);
            }
        }
        
        internal static string RecursiveOp {
            get {
                return ResourceManager.GetString("RecursiveOp", resourceCulture);
            }
        }
        
        internal static string DocsCommand {
            get {
                return ResourceManager.GetString("DocsCommand", resourceCulture);
            }
        }
        
        internal static string RemoveAllCommand {
            get {
                return ResourceManager.GetString("RemoveAllCommand", resourceCulture);
            }
        }
        
        internal static string DeleteRecycle {
            get {
                return ResourceManager.GetString("DeleteRecycle", resourceCulture);
            }
        }
        
        internal static string ConfigCommand {
            get {
                return ResourceManager.GetString("ConfigCommand", resourceCulture);
            }
        }
        
        internal static string ConfigSetCommand {
            get {
                return ResourceManager.GetString("ConfigSetCommand", resourceCulture);
            }
        }
        
        internal static string BulkCommand {
            get {
                return ResourceManager.GetString("BulkCommand", resourceCulture);
            }
        }
        
        internal static string CleanCommand {
            get {
                return ResourceManager.GetString("CleanCommand", resourceCulture);
            }
        }
        
        internal static string RemoveCommand {
            get {
                return ResourceManager.GetString("RemoveCommand", resourceCulture);
            }
        }
        
        internal static string SessionCommand {
            get {
                return ResourceManager.GetString("SessionCommand", resourceCulture);
            }
        }
        
        internal static string SessionSwitchCommand {
            get {
                return ResourceManager.GetString("SessionSwitchCommand", resourceCulture);
            }
        }
        
        internal static string SessionRemoveCommand {
            get {
                return ResourceManager.GetString("SessionRemoveCommand", resourceCulture);
            }
        }
        
        internal static string BulkDeleteCommand {
            get {
                return ResourceManager.GetString("BulkDeleteCommand", resourceCulture);
            }
        }
        
        internal static string QuietOption {
            get {
                return ResourceManager.GetString("QuietOption", resourceCulture);
            }
        }
        
        internal static string DryrunOption {
            get {
                return ResourceManager.GetString("DryrunOption", resourceCulture);
            }
        }
        
        internal static string NoPromptOption {
            get {
                return ResourceManager.GetString("NoPromptOption", resourceCulture);
            }
        }
        
        internal static string FilterOperand {
            get {
                return ResourceManager.GetString("FilterOperand", resourceCulture);
            }
        }
        
        internal static string SessionSwitchName {
            get {
                return ResourceManager.GetString("SessionSwitchName", resourceCulture);
            }
        }
        
        internal static string SessionRemoveName {
            get {
                return ResourceManager.GetString("SessionRemoveName", resourceCulture);
            }
        }
        
        internal static string PrintKeysOperand {
            get {
                return ResourceManager.GetString("PrintKeysOperand", resourceCulture);
            }
        }
        
        internal static string DocsModulesOperand {
            get {
                return ResourceManager.GetString("DocsModulesOperand", resourceCulture);
            }
        }
        
        internal static string GetConfigKey {
            get {
                return ResourceManager.GetString("GetConfigKey", resourceCulture);
            }
        }
        
        internal static string SetConfigKey {
            get {
                return ResourceManager.GetString("SetConfigKey", resourceCulture);
            }
        }
        
        internal static string SetConfigValue {
            get {
                return ResourceManager.GetString("SetConfigValue", resourceCulture);
            }
        }
        
        internal static string VerbosityOperand {
            get {
                return ResourceManager.GetString("VerbosityOperand", resourceCulture);
            }
        }
        
        internal static string IncludeDirsOp {
            get {
                return ResourceManager.GetString("IncludeDirsOp", resourceCulture);
            }
        }
        
        internal static string BulkMergeCommand {
            get {
                return ResourceManager.GetString("BulkMergeCommand", resourceCulture);
            }
        }
        
        internal static string BulkCopyCommand {
            get {
                return ResourceManager.GetString("BulkCopyCommand", resourceCulture);
            }
        }
        
        internal static string BulkMoveCommand {
            get {
                return ResourceManager.GetString("BulkMoveCommand", resourceCulture);
            }
        }
        
        internal static string CopyTargetDir {
            get {
                return ResourceManager.GetString("CopyTargetDir", resourceCulture);
            }
        }
        
        internal static string MoveTargetDir {
            get {
                return ResourceManager.GetString("MoveTargetDir", resourceCulture);
            }
        }
        
        internal static string CopyRetain {
            get {
                return ResourceManager.GetString("CopyRetain", resourceCulture);
            }
        }
        
        internal static string MoveRetain {
            get {
                return ResourceManager.GetString("MoveRetain", resourceCulture);
            }
        }
    }
}
