//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FsTag.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrintKeyDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrintKeyDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FsTag.Resources.PrintKeyDescriptions", typeof(PrintKeyDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path of the global configuration file..
        /// </summary>
        internal static string ConfigPath {
            get {
                return ResourceManager.GetString("ConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of all tagged files..
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path of the current-session index file..
        /// </summary>
        internal static string IndexPath {
            get {
                return ResourceManager.GetString("IndexPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path of the current-session label index..
        /// </summary>
        internal static string LabelIndexPath {
            get {
                return ResourceManager.GetString("LabelIndexPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of all valid print keys. Like the one you&apos;re looking at right now..
        /// </summary>
        internal static string PrintKeys {
            get {
                return ResourceManager.GetString("PrintKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw json of the global configuration file..
        /// </summary>
        internal static string RawConfig {
            get {
                return ResourceManager.GetString("RawConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw json of the current-session label index..
        /// </summary>
        internal static string RawLabelIndex {
            get {
                return ResourceManager.GetString("RawLabelIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data directory path of the current session..
        /// </summary>
        internal static string SessionPath {
            get {
                return ResourceManager.GetString("SessionPath", resourceCulture);
            }
        }
    }
}
